-- Challenges generated by Interview Architect
CREATE TABLE challenges (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    difficulty TEXT DEFAULT 'medium'
        CHECK (difficulty IN ('easy', 'medium', 'hard')),
    sdk_docs_url TEXT,
    sdk_docs_content TEXT,
    job_description_text TEXT,
    resume_text TEXT,
    generated_files JSONB NOT NULL,
    solution_hints TEXT,
    expected_bugs JSONB,
    language TEXT DEFAULT 'typescript',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Custom evaluation rubrics generated by Interview Architect
CREATE TABLE rubrics (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    challenge_id UUID REFERENCES challenges(id),
    criteria JSONB NOT NULL,
    total_weight INTEGER DEFAULT 100,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Interview sessions
CREATE TABLE sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    interviewer_id TEXT NOT NULL,
    candidate_name TEXT,
    challenge_id UUID REFERENCES challenges(id),
    rubric_id UUID REFERENCES rubrics(id),
    sandbox_id TEXT,
    status TEXT DEFAULT 'pending'
        CHECK (status IN ('pending', 'active', 'completed')),
    duration_minutes INTEGER DEFAULT 45,
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Setup chat history
CREATE TABLE chat_messages (
    id BIGSERIAL PRIMARY KEY,
    session_setup_id TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'tool_use', 'tool_result')),
    content TEXT NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Raw activity events from E2B sandbox (append-only)
CREATE TABLE events (
    id BIGSERIAL PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES sessions(id),
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    event_type TEXT NOT NULL
        CHECK (event_type IN (
            'claude_code_event',
            'terminal_output',
            'file_change',
            'command_executed',
            'session_start',
            'session_end'
        )),
    raw_content TEXT NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb
);

-- Opus 4.6 analysis insights (append-only)
CREATE TABLE insights (
    id BIGSERIAL PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES sessions(id),
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    insight_type TEXT NOT NULL
        CHECK (insight_type IN (
            'reasoning_update',
            'signal',
            'copilot_question',
            'phase_change',
            'summary'
        )),
    content JSONB NOT NULL,
    rubric_criterion TEXT
);

-- Indexes
CREATE INDEX idx_events_session ON events(session_id, timestamp DESC);
CREATE INDEX idx_insights_session ON insights(session_id, timestamp DESC);
CREATE INDEX idx_chat_setup ON chat_messages(session_setup_id, created_at);

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE events;
ALTER PUBLICATION supabase_realtime ADD TABLE insights;
ALTER PUBLICATION supabase_realtime ADD TABLE sessions;
